using Xunit;

namespace AttendanceManagement.EntityFrameworkCore;

[CollectionDefinition(AttendanceManagementTestConsts.CollectionDefinitionName)]
public class AttendanceManagementEntityFrameworkCoreCollection : ICollectionFixture<AttendanceManagementEntityFrameworkCoreFixture>
{

}
